name: AWS example workflow
on:
  push
env:
  AWS_REGION : "ap-northeast-2"
permissions:
  id-token: write
  contents: read
jobs:
  S3List:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::057845469470:role/11-test
          role-session-name: test
          aws-region: ${{ env.AWS_REGION }}
      - name: List s3
        run: |
          aws s3 ls
